sudo: required
language: python
matrix:
    include:
        - python: 2.7
          dist: precise
          env: TOXENV=py27
          addons:
              postgresql: "9.4"
        - python: 2.7
          dist: bionic
          env: TOXENV=py27
          addons:
              postgresql: "11"
        - python: 3.8
          dist: bionic
          env: TOXENV=py37
          addons:
              postgresql: "10"
        - python: 3.8
          dist: bionic
          env: TOXENV=py38
          addons:
              postgresql: "11"
        - python: 3.8
          dist: bionic
          env: TOXENV=py38
          addons:
              postgresql: "12"
        - python: 3.8
          dist: bionic
          env: TOXENV=py37
          addons:
              postgresql: "13"
install:
    - pip install tox
script:
    - tox
